Fix index error #15
PythonRail/Slay-The-Spire-in-Python pull request #18
Opened 2023-12-26 00:59 UTC by miketwo

Actually fixes #15 

The broken lines looked like this:
```python
common_potions: list[dict] = [potion for potion in potion_pool.values() if potion.get("Rarity") == "Common" and (potion.get("Class") == "All" or entity.player_class in potion.get('Class'))]
```

Note the `== "All"`

The filter was looking for "All" instead of the correct "Any". Because it had the wrong word, the list was empty, so when it tried to take the `[0]` element of an empty list, it crashed. (It should be noted that the bug will still be there if the `potion_pool` doesn't include at least 1 of each rarity of potion.)

You mentioned you're new at Python, so I'll use this as a teaching moment. There are a few things that could be improved here to avoid these errors in the future:

- **Indepedent functions.** The 3 lines with errors are essentially filters on the larger pool of potions. These filters could be their own small testable functions
- **Enumerations.** The error was a typo. If an Enum was used instead, such a typo would get caught during linting -- there would be a squiggly line under `Rarity.All` indicating a problem.
- **Potion classes.** Instead of a dict of dicts, if potions were a class, these attributes could again be checked by the linter.

2023-12-26 21:23 UTC, Vesper-arch requested changes
Thank you! Honestly a dumb mistake with the potions. I will say that the dictionaries that you fixed were intentional, I wanted to key each pool to a word for displaying, so just reverse that and I'll merge the changes.
Example: _common_cards is empty_ output: `"Common pool is empty"`

2023-12-28 22:27 UTC, miketwo commented
I can flip it back, but Python won't let you use a list as a key in a dictionary, because lists are mutable and keys can't be.

2023-12-28 22:30 UTC, Vesper-arch commented
Alr, you can just remove them cause I know that the pools will have the correct stuff in them. Plus the only reason they are there is because of circular import so I had to add that parameter.

2023-12-29 00:11 UTC, Vesper-arch approved these changes
Thank you for working on this. I don't have any more storage for codespaces so I can't do anything more until next month.

2023-12-29 00:11 UTC, merged